[from]
chain = "polygon"
datasource = "rpc" # big_query or rpc or file or chifra
dapp_type = "uniswap" # uniswap or aave
#http_proxy = "http://localhost:8080" # if network is bad, try use proxy
start = "2022-3-16"
end = "2022-3-17"

[from.uniswap]
pool_address = "0x9B08288C3Be4F62bbf8d1C20Ac9C5e6f9467d8B7"
ignore_position_id = false # if set to true, will not download uniswap proxy logs to get position_id. will save a lot of time

[from.aave]
tokens = [# address of erc20 token which avialable on aave
    "0x7ceb23fd6bc0add59e62ac25578270cff1b9f619",
    "0x2791bca1f2de4661ed88a30c99a7a9449aa84174"
]

[from.big_query] # if you want to download from big query, use this section, from.rpc/from.file will be ignored
auth_file = "./auth/airy-sight-361003-d14b5ce41c48.json" # google bigquery auth file

[from.rpc] # If you want to download from rpc interface, use this section, from.big_query/from.file will be ignored
end_point = "https://localhost:8545"
#auth_string = "Basic Y3J0Yzo3NKY3TjY" # auth string for rpc end point
#batch_size = 500 # default is 500
#keep_tmp_files = false
etherscan_api_key = "some_api_key" #


[from.chifra]
etherscan_api_key = "" # must fill if query etherscan for block, proxy must set.

[to] # decide output
type = "tick" # minute or tick or raw
save_path = "./sample-data"
keep_raw = true
skip_existed = true # if file has existed, will skip download. default is false

