# This is a sample to download uniswap data with chifra

[from]
chain = "ethereum"
datasource = "chifra"
dapp_type = "uniswap"
http_proxy = "http://localhost:7890"
start = "2025-1-8"
end = "2025-1-8"

[from.uniswap]
pool_address = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"
ignore_position_id = false
is_token0_base = false

[from.chifra]
etherscan_api_key = "" # Api key of etherscan, If this is set, query from etherscan will be faster.

[to]
type = "tick" # minute or tick or raw
save_path = "/data/uniswap/ethereum/usdc-eth-005"
skip_existed = true # if file has existed, will skip download. default is false
# keep_raw = true # keep raw files in every step, or only keep final result file. default is false
# file_type = "feather" # save file as csv or feather or parquet, default is csv
