# This is a sample to download uniswap data with big query

[from]
chain = "ethereum"
datasource = "big_query"
dapp_type = "uniswap"
http_proxy = "http://localhost:7890" # if you have a bad connection, you can use proxy
start = "2025-1-8"
end = "2025-1-8"

[from.uniswap]
pool_address = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"

[from.big_query]
auth_file = "~/airy-sight-XXXXXX-XXXXXXXXXXXXX.json"

[to]
type = "minute" # minute or tick or raw
save_path = "/data/uniswap/ethereum/usdc-eth-005"
skip_existed = true # if file has existed, will skip download. default is false
# keep_raw = true # keep raw files in every step, or only keep final result file. default is false
