[from]
chain = "ethereum"
datasource = "big_query" # big_query or rpc or chifra
dapp_type = "aave" # uniswap or aave
http_proxy = "http://localhost:7890"
start = "2025-1-1"
end = "2025-1-1"

[from.aave]
tokens = [
    "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
]

[from.big_query]
auth_file = "~/airy-sight-XXXXXX-XXXXXXXXXXXXX.json"

[to]
type = "minute" # minute or tick or raw
save_path = "/data/aave/ethereum"
skip_existed = true # if file has existed, will skip download. default is false
