[from]
chain = "ethereum"
datasource = "big_query"
dapp_type = "uniswap"
start = "2025-1-8"
end = "2025-1-8"

[from.uniswap]
pool_address = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"

[from.big_query]
auth_file = "~/zelos/code/demeter-fetch/auth/airy-sight-XXXXXX-XXXXXXXXXXXXX.json"

[to]
type = "minute" # minute or tick or raw
save_path = "/data/uniswap/ethereum/usdc-eth-005"


file_type = "feather" # save file as csv or feather or parquet, default is csv
