[from]
chain = "ethereum"
datasource = "big_query"
dapp_type = "uniswap_v4"
start = "2025-2-9"
end = "2025-2-9"

[from.uniswap]
# id of uniswap v4 pool
pool_address = "0x21c67e77068de97969ba93d4aab21826d33ca12bb9f565d8496e8fda8a82ca27"

[from.big_query]
auth_file = "~/airy-sight-XXXXXX-XXXXXXXXXXXXX.json"


[to]
type = "tick" # minute or tick or raw
save_path = "/data/uniswap-v4/ethereum/eth-usdc-005"
skip_existed = true # if file has existed, will skip download. default is false
