[from]
chain = "ethereum"
datasource = "rpc"
dapp_type = "uniswap"
start = "2025-1-8"
end = "2025-1-8"

[from.uniswap]
pool_address = "0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640"

# if you have your own ethereum node, you can follow this setting

[from.rpc]
end_point = "http://192.168.0.100:8545"
# Set this if the rpc is protected by basic auth(can be set by nginx etc),
# This will append "Authorization=XXXXXX" in request header
auth_string = "Basic sdfagasdgasdfasdf"
# block count in one get_logs query. You can set this number larger
batch_size = 2000
# Demeter-fetch have to query start/end block number in a day from etherscan, or polygonscan etc.
etherscan_api_key = "Your key at XXXScan"
# More thread if your node is fast enough
thread = 10


[to]
type = "tick" # minute or tick or raw
save_path = "/data/uniswap/ethereum/usdc-eth-005"
skip_existed = true # if file has existed, will skip download. default is false
